title: 壹书壹网站
description: 研究基于 Jekyll 编写和发布图书的技术！
theme: just-the-docs
favicon_ico: "/assets/images/favicon.ico"
url: 

collections:
  chapters:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    name: Chapters

aux_links:
  书稿: https://github.com/jekyll-pub/one-book-one-site
